apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: frontend
          image: frontend:b98f8b69185d16b9b676bf42238f1b61a211def8
